[package]
name = "did-integrity"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
signature = "2.1.0"
