[package]
name = "did-integrity"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
multibase = "0.9.1"
signature = "2.1.0"
thiserror = "1.0.47"
